### ISSUE TITLE
Siirto vignettes kansioon

### ISSUE THREAD

**Issue by jhuovari** [pttry/KT162R#1]
Siirrä @jalasalmi kaikki kuvio-tiedostot vignettes kansioon. R-kansiossa saa olla vain funktiomäärityksiä, muuten pakettia ei voi oikein ladata.

**Comment by jalasalmi** [comment]
Hyvä tietää, yritän ehtiä tutustua tuohon markdowniin jossain vaiheessa. Ennen sitä: onko mitään paikkaa, jonne sopivat R tiedostot, joissa kuvien piirto?

**Comment by jhuovari** [comment]
Nekin voi laittaa sinne vignettes kansioon.
